Django Project/HotelBooking/Accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .import views
# from .views import HotelSearchAPIView

from .views import HotelSearchAPIView, search
urlpatterns = [
    path('api/search/', HotelSearchAPIView.as_view(), name='hotel-search-api'),
    path('search/', search, name='hotel-search'),

    

    
    
    
    path('about/',views.About,name='about'),
    path('service/',views.Services,name='service'),
    path('terms/',views.tersms,name='terms'),
    
    
    

    

    # Admin

    path('show/',views.category_view,name='show'),
    path('cat/<int:id>/',views.userclick_view,name='cat'),


    path('Adminlogin/',views.Admin_Login.as_view(),name='Adminlogin'),
    path('register/',views.register_user,name='register'),
    path('logout/',views.Logout_page,name='logout'),
    path('AddHotel/',views.AddHotel,name='AddHotel'),
    path('deleteh/<int:id>/',views.deleteh,name='deleteh'),
    path('view/<int:id>/',views.showalldata,name='view'),
    path('search/',views.search,name='search'),

    
    # path('api/search/', HotelSearchAPIView.as_view(), name='hotel-search-api'),

    path('<int:id>/',views.updateHotelData,name='update'),
    path('catgory/',views.catadd,name='catgory'),

    path('BookingData/',views.Bookingdata,name='BookingData'),

    
    path('AdminCancelBooking/<int:id>/',views.AdminCancelBooking,name='AdminCancelBooking'),
    path('AdminUSerDelete/<int:id>/',views.AdminUSerDelete,name='AdminUSerDelete'),

    path('AdminData/<int:id>/',views.AdminData,name='AdminData'),

# ------------------- User --------------------------------------------------------------------------------------------------------


    
    path('',views.user_categoryview,name='userHome'),
    path('cat/<int:id>/',views.userclick_view,name='cat'),
    path('userlogin',views.Customer_Login.as_view(),name='userlogin'),

 

 
    path('userdata/',views.Userdata,name='userdata'),
   

    path('UpdateUserData',views.UpdateUserData,name='UpdateUserData'),
    path('userprofile',views.UserProfile.as_view(),name="userprofile"),

    path('Userbookingdata',views.UserBookingData.as_view(),name="Userbookingdata"),

    path('CancelBooking/<int:id>/',views.CancelBooking,name='CancelBooking'),

    path('updatebook/<int:id>/',views.updateBookingUser,name='UpdateBooking'),

    path('book-hotel/<int:id>/',views.HotelBookingView.as_view(),name='book_hotel'),
    # path('<int:id>/',views.userBooking,name='userBooking'),

   

    

]

Django Project/HotelBooking/HotelBooking/urls.py
from django.contrib import admin
from django.urls import path,include
from .import urls

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('',include('Accounts.urls')),
    path('admin/', admin.site.urls),
    
    
    

]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django Project/HotelBooking/Accounts/models.py
from django.contrib.auth.models import User
from django.db import models



# Create your models here.



class Categeroies(models.Model):
    title= models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title   


class Hotel(models.Model):
    
    Name = models.CharField(max_length=200)
    location = models.TextField()
    HotelInfo = models.TextField()
    image = models.ImageField(upload_to='image/')
    Ammount =models.IntegerField(max_length=5)
    User1 = models.CharField(max_length=100)
    upload_date = models.DateField(auto_now_add=True)
    cat=models.ForeignKey(Categeroies,on_delete=models.CASCADE)

    
    def __str__(self) :
         return f"{self.Name} - {self.location} -{self.cat}"





class HotelBooking(models.Model):
    hotel= models.ForeignKey(Hotel  , related_name="hotel_bookings" , on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_bookings" , on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    email=models.EmailField()
    
    BOOKING_TYPE = (
        ('CASH', 'Cash'),
        ('NET_BANKING', 'Net Banking'),
    )
    booking_type = models.CharField(max_length=20, choices=BOOKING_TYPE)
    
    ROOM_TYPES = (
        ('SINGLE', 'Single'),
        ('DOUBLE', 'Double'),
    )
    room_type = models.TextField( choices=ROOM_TYPES)
    
    
    def calculate_total_price(self):
       
        price_per_night = self.hotel.price  

        # Calculate the number of days between start_date and end_date
        num_days = (self.end_date - self.start_date).days

        # Calculate the total price
        total_price = num_days * price_per_night

        return total_price

    
'''
class Customer(models.Model):
    Username=models.CharField(max_length=100)
    Fisrt_Name=models.CharField(max_length=100)
    Last_Name=models.CharField(max_length=100)
    Email=models.EmailField()
    Location=models.CharField(max_length=100)
    contact=models.CharField(max_length=20)
    Password=models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.Fisrt_Name
    '''

    

Django Project/HotelBooking/templates/Admin_AddHotel.html
{% extends 'Admin_base.html' %}
{% load static %}

{% block body %}


<style>
  #fixe{
    background: url('{% static "image/6.jpeg" %}');
    background-size: cover;
    background-position: start;
   
  }

  .forms-s{
    font-weight: bold;
    padding-top: 5px;
  }

  #sec-add{
    
    background: transparent;
    border: black line;
    box-shadow: 25px;
    color: rgb(3, 16, 1);
    font-size: larger;
  }
</style>


<div class="row">
  <div class="col-sm8" id="fixe">

    
<div class="container col-sm-5 mt-5 mx-5 p-4 shadow-lg" id="sec-add">
  <h2 class="mb-3"> <b> ADD HOTEL </b></h2><hr>
          <form action="" method="POST" class="forms-s"  enctype="multipart/form-data">
              {% csrf_token %}
              {% if messages %}
          {{message.tags}}
          
        <div class="alert alert-primary" role="alert">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
          </div>
          {% endif %}
          
  
      {{forms.as_p}}
      <input class="btn btn-success mt-3" type="submit" name="submit" id="" value="submit" >
      <input class="btn btn-danger mt-3" type="reset" name="submit" id="" value="clear" >
  
      </form>
    </div>




 









<div class="col-sm-9 mt-5 my-5 mx-auto sec-col">
  {% if forms %}
  <table class="table bg-transparent"  >

      <thead>
      <tr>
          <th scope="col"> ID </th>
          <th scope="col"> Name </th>
          <th scope="col"> Location </th>
          <th scope="col"> HotelInforamation </th>
          <!-- <th scope="col"> image </th> -->
          <th scope="col"> update </th>
          <th scope="col"> Delete </th>
      </tr>
      </tr>
  </thead>
  <tbody>
       {% for i in m %}
      <tr>
        <td><b>{{i.id }}</b></td>
        <td><b>{{i.Name}}</b></td>
        <td><b>{{i.location}}</b></td>
        <td ><b>{{i.HotelInfo|truncatechars:10}}</b></td>
        <!-- <td><a href="/media/{{i.image}}"></a>{{i.image}}</td>
       -->
  
            <td>
              <a href="{% url 'update' i.id %}" class="btn btn-warning  ">Update</a></td>

            <td>
              <form action="{% url 'deleteh' i.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="delete" class="btn btn-danger">
                </form>
          </td>


          


      </tr>
      {% endfor %}
  </tbody>
{% else %}

{% endif %}

  </table>

</div>


  </div>
</div>












{% endblock body %}

Django Project/HotelBooking/templates/Admin_login.html
{% extends 'admin_base.html' %}

{% block body %}
   
<!-- <br><br><br> -->

<!--

<div class="container card shadow-lg mt-5 card p-4 col-3" style="background-color: rgb(247, 251, 250);" >
    <form method="POST" action="">
        <h2> <b>Admin Login </b></h2><hr>

        {% csrf_token %}
        {% if messages %}
        {{message.tags}}
      <div class="alert alert-primary" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        </div>
        {% endif %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label"><b>UserName</b></label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
          <div id="emailHelp" class="form-text">Enter Your UserName As It Is</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label"><b>Password</b></label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
                <button type="submit" class="btn btn-success">Submit</button>
                <button type="reset" class="btn btn-danger">clear</button>
      </form>
    
      
      
</div>html

-->

<!--Login form -->

<!-- Section: Design Block -->
<section class="background-radial-gradient overflow-hidden">
  <style>
    .background-radial-gradient {
      background-color: hsl(218, 41%, 15%);
      
      background-image: radial-gradient(650px circle at 0% 0%,
          hsl(218, 41%, 35%) 15%,
          hsl(218, 41%, 30%) 35%,
          hsl(218, 41%, 20%) 75%,
          hsl(218, 41%, 19%) 80%,
          transparent 100%),
        radial-gradient(1250px circle at 100% 100%,
          hsl(218, 41%, 45%) 15%,
          hsl(218, 41%, 30%) 35%,
          hsl(218, 41%, 20%) 75%,
          hsl(218, 41%, 19%) 80%,
          transparent 100%);
          
    }

    #radius-shape-1 {
      height: 220px;
      width: 220px;
      top: -60px;
      left: -130px;
      background: radial-gradient(#44006b, #ad1fff);
      overflow: hidden;
      
    }

    #radius-shape-2 {
      border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;
      bottom: -60px;
      right: -110px;
      width: 300px;
      height: 300px;
      background: radial-gradient(#44006b, #ad1fff);
      overflow: hidden;
    }

    .bg-glass {
      background-color: hsla(0, 0%, 100%, 0.9) !important;
      backdrop-filter: saturate(200%) blur(25px);
    }
  </style>

  <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
    <div class="row gx-lg-5 align-items-center mb-5">
      <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
        <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
          The best offer <br />
          <span style="color: hsl(218, 81%, 75%)">for your bookings</span>
        </h1>
        <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
          Temporibus, expedita iusto veniam atque, magni tempora mollitia
          dolorum consequatur nulla, neque debitis eos reprehenderit quasi
          ab ipsum nisi dolorem modi. Quos?
        </p>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
        <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
        <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>

        <div class="card bg-glass">
          <div class="card-body bg px-4 py-5 px-md-5">
            <form method="POST" action="" >
              <!-- 2 column grid layout with text inputs for the first and last names -->
              <h2 class="text-center"> <b> ADMIN LOGIN </b></h2><hr>

              {% csrf_token %}
              {% if messages %}
              {{message.tags}}
            <div class="alert alert-primary" role="alert">
              {% for message in messages %}
              {{ message }}
              {% endfor %}
              </div>
              {% endif %}
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label" ><b>UserName</b></label>
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username" placeholder="Enter UserName" >
                <div id="emailHelp" class="form-text" >Enter Your UserName As It Is</div>
              </div>
              <!-- <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label"><b>Password</b></label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password">
              </div> -->
                
            
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label"><b>Password</b></label>
                <div class="input-group">
                  <input type="password" class="form-control" id="exampleInputPassword1" name="password"
                    placeholder="Enter Password">
                  <div class="input-group-append">
                    <span class="input-group-text">
                      <input type="checkbox" onclick="showPassword()"> Show Password
                    </span>
                  </div>
                </div>
              </div>



              <!-- Checkbox -->
              <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                <label class="form-check-label" for="form2Example33">
                  Subscribe to our newsletter
                </label>
              </div>
              

              <!-- Submit button -->
             
              <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
              <button type="reset" class="btn btn-danger btn-block mb-4">clear</button>

              <!-- Register buttons -->
              <div class="text-center">
                <p>or sign up with:</p>
                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-facebook-f"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-google"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-twitter"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-github"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Design Block -->


<script>
  function showPassword() {
    var passwordInput = document.getElementById("exampleInputPassword1");
    if (passwordInput.type === "password") {
      passwordInput.type = "text";
    } else {
      passwordInput.type = "password";
    }
  }
</script>



<!-- <br><br><br><br><br><br> -->


{% endblock body %}

{% block css %}






{% endblock css %}

Django Project/HotelBooking/templates/Booking.html
{% extends 'Admin_base.html' %}
{% load static %}

{% block body %}

<!DOCTYPE html>
<html>
<head >
    <title>Hotel Booking Form</title>
</head>
<body >

    

<div class=" container-fluid  " style="display: flex;" id="Book4">

    <div class="container card rounded-lg col-5 mt-5 card mx-5 p-4 border-dark mb-5 bg-transparent " >
  
      <h1 class="mb-3 text-center"> <b> BOOK YOUR HOTEL {{ hotel.name }}</b></h1>
      <hr>
      <form action="" method="POST">
        
        {% if messages %}
        {{message.tags}}
        <div class="alert alert-primary" role="alert">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
        </div>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}

        <div >
          <h5 class="total_price " >Total Price :
            <span id="totalprice"></span> RS
          </h5>
        </div>

        <div style="float: inline-end;">

          <button type="submit" class="btn btn-success">Book Now</button>
          <button type="reset" class="btn btn-primary">Cancel</button>
          <td>
            <a href="{% url 'userHome' %} " class="btn btn-danger "> Back </a>
          </td>

        </div>
       
       
      </form>
    </div>


<!-- 
    <div class="col-5 mt-5 mx-auto card mb-5">
      <h1 class="text-center mt-5" >HOTEL DETAILS</h1>
      

    </div>
   -->
  </div>

  <script>

   
    // function calculateTotal(){
    //   var Price = "{{hotel.Ammount}}";
    //   // var start_date = Price;
    //   var start_date=document.getElementById('start_date').value;
    //   alert(start_date)
    //   var end_date=document.getElementById('end_date').value;
    //   alert(end_date)
    //   var num_days = (end_date-start_date).days;
    //   var total=num_days*Price
    //   document.getElementById('totalprice').innerHTML =total;
    // }

    
    $(document).ready(function () {
        // Function to calculate total amount
        function calculateTotalAmount() {
            var startDate = new Date($('#id_start_date').val());
            var endDate = new Date($('#id_end_date').val());

            // Assuming your price is stored in a variable called 'Ammount' in the HTML template
            var price = parseInt('{{ hotel.Ammount }}');

            // Calculate the number of days between start and end date
            var days = Math.ceil((endDate - startDate) / (1000 * 60 * 60 * 24));

            // Calculate total amount
            var totalAmount = price * days;

            // Display the total amount
    document.getElementById('totalprice').innerHTML =totalAmount;

            // $('#total_amount').text('Total Amount: $' + totalAmount);
        }

        // Call the function on page load
        calculateTotalAmount();

        // Attach event listeners to start_date and end_date fields
        $('#id_start_date, #id_end_date').change(function () {
            calculateTotalAmount();
        });
    });





    document.addEventListener('DOMContentLoaded', function() {
        var today = new Date().toISOString().split('T')[0];
        document.getElementById('start_date').min = today;
        document.getElementById('end_date').min = today;

        // Ensure start date is greater than or equal to the current date
        document.getElementById('start_date').addEventListener('change', function() {
            var startDate = document.getElementById('start_date').value;
            var today = new Date().toISOString().split('T')[0];

            if (startDate < today) {
                document.getElementById('start_date').value = today;
            }
            // Set the minimum for the end date as the selected start date
            document.getElementById('end_date').min = startDate;
        });
    });


    
</script>
</body>
</html>





<style>
#Book4{
  background: url('{% static "image/6.jpeg" %}');
  background-size: cover;
  background-position: start;
 
}

</style>





{% endblock body %}

Django Project/HotelBooking/templates/UpdateUserData.html
{% extends 'Admin_base.html' %}
{% load static %}
{% block css %}

{% endblock css %}


{% block body %}


<style>
  .sec-dis1 {
   
    background: url('{% static "image/6.jpeg" %}');
    background-size: cover;
    display: flow-root;
    bottom: 0;
  }
  #sec-fod{
    background-color: rgba(255, 255, 255, 0.177);  
    backdrop-filter: blur(5px);
  }

  
</style>

<div class=" container-fluid sec-dis1  ">

  <div class="card rounded-lg col-sm-5 mt-5 card mx-5 p-4 border-dark mb-5 " id="sec-fod" style="height: 30%; width: 40%;" >

    <h1 class="mb-3 text-center" > <b> UPDATE USER PROFILE </b></h1>
    <hr>
    <form action="" method="POST">
      {% csrf_token %}
      {% if messages %}
      {{message.tags}}
      <div class="alert alert-primary" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
      </div>
      {% endif %}
  
      {{form.as_table}}
      <input class="btn btn-success mt-3" type="submit" name="submit" id="" value="Submit">
      <input class="btn btn-danger mt-3" type="reset" name="clear" id="" value="clear">
  
  
    </form>
  </div>

</div>










{% endblock body %}

Django Project/HotelBooking/templates/about.html
{% extends 'admin_base.html' %}
{% load static %}



{% block body %}


<!DOCTYPE html>
<html>
<head>
    <title>Hotel About Us</title>
    <style>
        /* CSS for the About Us section */
        #about-us {
            
            padding: 20px;
            margin: 40px 40px;
           

            
        }

        #about-us h2 {
            color: #333;
            font-size: 40px;
            text-align: center;
            margin-bottom: 25px;
            font-weight: bold;
            font-style: oblique;
            background-color: chartreuse;
            padding: 20px 20px ;
            border-radius: 35px;
        }

        #about-us p {
            font-size: 16px;
            line-height: 1.5;
            font-size: 25px;
            flex-direction: initial;
            
        }
    </style>
</head>
<body>
    <div id="about-us">
        <h2>About Our Hotel</h2>
        <p>Welcome to our luxurious and comfortable hotel. At our hotel, we strive to make your stay memorable and enjoyable. Whether you're here for a business trip or a relaxing vacation, we provide top-notch services and amenities to meet your every need.</p>
        <p>Our dedicated staff is committed to making your experience with us truly special. We offer spacious and well-appointed rooms, exquisite dining options, and a variety of recreational activities to ensure your stay is nothing short of perfect.</p>
        <p>Explore our website to learn more about our facilities and book your stay with us today. We can't wait to welcome you and make your visit a remarkable one.</p>
    </div>
</body>
</html>








<br><br><br><br><br><br>
{% endblock body %}

Django Project/HotelBooking/templates/admin_navbar.html
{% load static %}



<!--Nvbar Search Website Logo Here -->

<nav class="navbar  navbar-dark bg-dark ">
  <div class="container-fluid ">
    <a class="navbar-brand" href="{% url 'show' %}"><b> <span style="color: chartreuse;"> P A R A D I S E </span>
      </b></a>
    <h3 class="text-light" id="slogan">search, find and book your hotel worldwide online </h3>

    <form class="d-flex" action="{% url 'search' %}" method="POST">
      {% csrf_token %}
      <input class="form-control me-2" type="search" name="search" placeholder="Search a Hotel" aria-label="Search">
      <button class="btn btn-danger" value="search" style="background-color: rgb(55, 255, 0); color:black;"
        type="submit">Search</button>




    </form>

  </div>
</nav>

<!--Navbar Here-->

<nav class="navbar navbar-expand-lg  navbar-dark bg-primary shadow-lg text-dark sticky-top">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="#"><b> <span style="color: chartreuse;"> P  A  R  A  D  I  S  E </span> </b></a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated == False %}
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav h5 sec-li">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'userHome' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Sign-In
            </button>
            <div class="dropdown-menu " aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'userlogin' %}">User Login</a>
              <a class="dropdown-item" href="{% url 'Adminlogin' %}">Admin Login</a>
            </div>
          </div>

          {% elif user.is_staff %}
        <ul class="navbar-nav h4 my-1 mx-4 " id="sec-li">

          <li class="nav-item">
            <a class="nav-link " href="{% url 'show' %}">Home</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'BookingData' %}">Booking Data</a>
          </li>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'AddHotel' %}">Add Hotel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catgory' %}">Add Catogaries</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userdata' %}">Customer Data</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
          </li>
       

          
      </ul>
      <ul class="navbar-nav">
      <li class="nav-item  p-2 ">
        <!-- <h3 style="justify-content: last baseline;" > welcome {{request.user}}</h3> -->
        <a href="{% url 'userprofile' %}"> <i class="bi bi-person-circle h3" style="justify-content: flex-end; color: black;">  </i> </a> <b class="h3">welcome {{request.user}}</b>
      </li>
    </ul>

        {% else %}
        <ul class="navbar-nav h3 mx-4 my-1 " id="sec-li">
        <li class="nav-item  ">
         
          <a class="nav-link" href="{% url 'userHome' %}">Home</a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="{% url 'Userbookingdata' %}"> Your Booking</a>
        </li>

<!--         
        <li class="nav-item">
          <a class="nav-link" href="#"> Update Booking</a>   
        </li>  -->


        <li class="nav-item">
          <a class="nav-link" href="{% url 'UpdateUserData' %}"> Update Profile</a>   
        </li> 

        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'userprofile' %}"> Profile </a>   
        </li> 

        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">logout</a>
        </li>

       
      </ul>
    </ul>
    <ul class="navbar-nav">
    <li class="nav-item  p-2 ">
      <!-- <h3 style="justify-content: last baseline;" > welcome {{request.user}}</h3> -->
      <a href="{% url 'userprofile' %}"> <i class="bi bi-person-circle h3" style="justify-content: flex-end; color: black;">  </i> </a> <b class="h3">welcome {{request.user}}</b>
    </li>
  </ul>



        {% endif %}

       
        

     
    </div>
   
  



  </div>

</nav>



{% block css %}




<style>
  #slogan {

    position: relative;
    color: aliceblue;
    animation: slide 10s linear infinite;

  }

  #sec-li li a:hover {
   
    color: #030600fc;
    cursor: pointer;
  }

  @keyframes slide {
    to {
      -moz-transform: translateX(30%);
      -webkit-transform: translateX(30%);
      transform: translateX(30%);
    }

    from {
      moz-transform: translateX(-30%);
      -webkit-transform: translateX(-30%);
      transform: translateX(-30%)
    }
  }
</style>





{% endblock css %}



{% block js %}




{% endblock js %}

Django Project/HotelBooking/templates/category.html
{% extends 'admin_base.html' %}
{% load static %}

{% block body %}




<style>
    #fixed123{
      background: url('{% static "image/6.jpeg" %}');
      background-size: cover;
      background-position:center;
     
    }
  
    .forms-se1{
      font-weight: bold;
      padding-top: 5px;
      
    }
    #sec-update1{
        background: transparent;
        border: black line;
        box-shadow: 25px;
        color: rgb(3, 16, 1);
        font-size: larger;
       
    }
  </style>




<div class="container-fluied mx-auto  p-4  " id="fixed123">


    <div class="container col-sm-4 card border-dark mx-1 mt-5 p-4 mb-5 me-5" id="sec-update1" >
    
        <h2 class="mb-3 text-center " style="color: rgb(12, 15, 12); text-shadow: 35px;" > <b> ADD CATEGORY</b></h2><hr>
                <form action="" method="POST" class="forms-se1"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if messages %}
                {{message.tags}}
              <div class="alert alert-primary" role="alert">
                {% for message in messages %}
                {{ message }}
                {% endfor %}
                </div>
                {% endif %}
        
            {{form.as_p}}
            <input class="btn btn-success mt-3" type="submit" name="submit" id="" value="submit" >
            <input class="btn btn-danger mt-3" type="reset" name="submit" id="" value="clear" >
        
            </form>
          </div>
          

          
    
        </div>

        




{% endblock body %}